### PR TITLE
add config.js to enable define env variable

### PR DESCRIPTION
**Pull request by rickywu**
I have verified leave config.js blank will use default config

If want to use costome settings, just set like this:
window.DRAWIO_GITLAB_URL = 'http://mygitlab.net';
window.DRAWIO_GITLAB_ID = 'xxxx';

Also env variable can be injected by docker-entrypoint.sh to write one config.js before startup
see this PR https://github.com/fjudith/docker-draw.io/pull/30

### CODE REVIEW

**Comment by davidjgraph** [comment]
Sorry, but this incorrect. Simply spliting particular variables into another file, other than init.js, is both inconsistent and doesn't solve anything anymore than the current method.

If these variable go into config.js, the rest of the variable have to, as well. Therefore, rather than write the whole config.js file in a build step, you'll have to regex the value, otherwise you won't see newly added variables.

So, you might as well just regex init.js.

**Comment by rickywu** [comment]
@davidjgraph 
But currently not support bind variable at runtime, must bind at compile time.
If move to config.js, we can bind it before startup app at runtime.

**Comment by davidjgraph** [comment]
That doesn't question the issues I raised. How can it be justified to move only those two variables and not the others in init?

**Comment by davidjgraph** [comment]
Slightly delayed, but yes, I agree :).

11.2.9 adds pre and post config JS files, https://github.com/jgraph/drawio/tree/master/src/main/webapp/js , along the lines you describe.

**Comment by rickywu** [comment]
Glad to hear that.

**Pull request closed without merging**
