### PR TITLE
overall introduction of openstack stencil pack

### PR DESCRIPTION
**Pull request by chateaulav**
This should provide the main parts, as I know it is time consuming to develop. let me know if you see anything I may have missed, as this should provide base icons for resources maintained under there opensource projects as seen from the links in issue #2738

### CODE REVIEW

**Comment by chateaulav** [comment]
@egrimate just pinging to see if you need anything from me to help your review?

**Comment by davidjgraph** [comment]
We can't promise anything as the project is officially no contributions (see README), but we'll take a look as time allows (just a lot of holidays coming up for the 2 weeks of easter).

**Comment by clementduveau** [comment]
Hello, as stated, drawio is not open to contribution given the complexity of the project.
Adding stencils is not high complexity and can't bring breaking changes nor regressions. However, I can understand if no contributions are accepted. I would like to have a firm answer on if it's of value to you to get stencils proposals, or should I find another way to provide icons from commonly used tools in my org ?

**Comment by davidjgraph** [comment]
I'm not going to integrate this PR, no.

**Comment by chateaulav** [comment]
Thank you for your consideration, as I understand. The original intent was that these icons would be beneficial globally as AWS, Azure, and Google Cloud are already supported and integrated, and OpenStack is the number one open-source Cloud infrastructure project globally used.  Thank you again!

**Pull request closed without merging**
