### PR TITLE
fix "Manual Input" shape in flowchart.xml

### PR DESCRIPTION
**Pull request by Pwuts**
I was experiencing some weird issues with the "Manual Input" shape (see #623) and I ended up scrolling `flowchart.xml`. I couldn't find the cause of the problem but I did find out that the XML describes three round corners and one sharp corner.
I added an arc to the fourth corner to fix this.

### CODE REVIEW

**Comment by alderg** [comment]
Does not fix the shape.
manual-input-pr-622
. [Here](https://www.draw.io/#RrZPBUsMgEIafJsd2CEyrXlNbPVgvHcdjZyfQwBRCpMSkPr0gkDT20HHGU5aPn2XZ%2FZORleqfDDR8qymTGUa0z8hjhnGO0YP7eHIO5H5BAqiMoFE0gp34YhGiSFtB2WkitFpLK5opLHVds9JOGBiju6nsoOX01gYqdgV2Jchr%2Bi6o5ekVaOTPTFQ83ZyjuKMgiSM4caC6u0BknZGV0dqGSPUrJn3zUl%2BQ3ovN22vxYZbL4362zYsXPAvJNn85MjzBsNr%2Bb2ocUn%2BCbGO%2F4lvtOTWQWyVdlGekOFmjj0MbsSccGq9TfeXtMz9I3ZUcjJ0rqFuQe1E3rau56LiwbNdA6dWd0zpmdFtT5stDPlWwDl64GEwZnYTv3DIWyYxl%2Fa%2Bp3mhJPszJGZxpxaw5u3P9MOyQJ3p7GZfdaJTBDvzCJEkH0ZvVkHnsvwviCNJydMrP3sX%2FRtbf) is a test case.

**Comment by alderg** [comment]
Feel free to submit another PR, but I've updated the XML manually and got the above result, so please check your PR against the above test case before submitting. Thanks!

**Comment by Pwuts** [comment]
I don't see how to edit the shape XML in the UI

**Comment by alderg** [comment]
You are probably editing the wrong shape. Please click [here](https://www.draw.io/#RrZPBUsMgEIafJsd2CEyrXlNbPVgvHcdjZyfQwBRCpMSkPr0gkDT20HHGU5aPn2XZ%2FZORleqfDDR8qymTGUa0z8hjhnGO0YP7eHIO5H5BAqiMoFE0gp34YhGiSFtB2WkitFpLK5opLHVds9JOGBiju6nsoOX01gYqdgV2Jchr%2Bi6o5ekVaOTPTFQ83ZyjuKMgiSM4caC6u0BknZGV0dqGSPUrJn3zUl%2BQ3ovN22vxYZbL4362zYsXPAvJNn85MjzBsNr%2Bb2ocUn%2BCbGO%2F4lvtOTWQWyVdlGekOFmjj0MbsSccGq9TfeXtMz9I3ZUcjJ0rqFuQe1E3rau56LiwbNdA6dWd0zpmdFtT5stDPlWwDl64GEwZnYTv3DIWyYxl%2Fa%2Bp3mhJPszJGZxpxaw5u3P9MOyQJ3p7GZfdaJTBDvzCJEkH0ZvVkHnsvwviCNJydMrP3sX%2FRtbf) and then click edit shape. Note that the shape you are editing is not the Manual Input in the flowchart section, it's a shape that is no longer being used in flowchart.xml and that is kept there for backwards compatibility.

**Comment by Pwuts** [comment]
Shape I get when I click your link:
image

"Manual Input" shape from "Advanced" section:
image

"Manual Input" shape from "Flowchart" section:
image

Last two shapes both have the wrong perimeter connectors.

Which shape should I be editing then? And where is the "edit shape XML" button? :)

**Comment by Pwuts** [comment]
I found the Edit Shape button, it took me a while because it's only on the shape you added and not on the "prefab" shapes in the stencils. :)
[tadaa](https://www.draw.io/#RrZRds5owEIZ%2FjTPtRWf4Fi9FBBWQ40FAvekEiIACwRAE%2FPUNFfU4vWlnesNkn2w2ZGffd8TP8lbHoEwsFMFsxDFRO%2BLVEccJMkO%2FPejugJPkO4hxGt0R%2BwJOeoMDHM7FdRrB6i2RIJSRtHyHISoKGJI3BjBGzXvaEWXvt5Yghn8AJwTZn9RPI5LcqSwyL76AaZw8bmaZYScHj%2BQBVAmIUPMF8fMRP8MIkfsqb2cw63v36AuDfqaau1YuWJLOP39YrGJyP%2B7FtH858nwChgX5v6W5e%2BkryOqhX8NbSfdoYELyjK7YEa9UBKPzs41cTxJQ9nkVgUWYZt9uXmAGyGrmHw04pTOVzoqy2jPe9oIC%2Fsx82HqgGPiEGAse2Ym6C1x9bqghc87Uuqnssa2O9%2F70ULv%2BLG6cZT5bTHfM%2Blxv1FaRhISIWgVkBum0LL86ucnq1AFrxWoHvdkY06tlNNZxo2r78OQcqszsdGFSed7ZWWGA%2FPnaEhtNZELaJFeT2c7Yb%2FK9Z7jben%2FBcj6deay5RcD6NIEid77tCpXr5%2F5Ccy6BBdPrTZZ1uCB7IxHyihaZeeB4Pkh2YLrdgf7SVg9qiqPVkslWxqGxWQ1LENSSry%2FzxTimOdqh5VohFKkqNGvJs0WsH8zOlHmnHmtSDkwl2hYX0RbKxbGLF%2BzYXGWaO8GYHq2WU4OEfHda7RG9DVeJEW62l8bKQBeTerYMvWmgqp5Z26AJPTObB7oQ1zwk2pLJMSanesx1ZS6EJXEike9rTHb%2BKcFjPec8XprQSwpifzL9zpkGF0PwKkgj0Z3cnOK2a9Wd1GmLde10bSAeyqtqYR1%2FFs1aqczPHc20doV%2FWnzczgHV2BZ7ql9Sarc4Vn5rh1e%2F07lpkpRApwRhPzwNNR7KMKqLCPbTyvSTdXcSTqRrgMPBWLgxDf9SDoNsrhAT2H4xg0EeOkQ5JLijKe1T%2B%2Fcjg9VJQ9i8fOPpDskXz3jkgcGq4mfllxzpYlDkI3wZx%2B%2B9L%2B7Lz38B)

**Comment by Pwuts** [comment]
> Note that the shape you are editing is not the Manual Input in the flowchart section, it's a shape that is no longer being used in flowchart.xml and that is kept there for backwards compatibility.
Where is the Manual Input shape in the flowchart section located now? I could only find the string "Manual Input" in one XML file, `flowchart.xml`. Was it moved to `Shapes.js`?

**Comment by alderg** [comment]
Yep, line 2052.

**Comment by alderg** [comment]
The numbers would be hardcoded, you'd have to implement a perimeter for the manual input (eg. Shapes.js line 1475) as the shape is configurable via the yellow handles.

**Comment by alderg** [comment]
Bounds is the bounding box (mxRectangle), vertex is vertex (mxCellState), next is the next point on the edge (mxPoint) and orthogonal is a boolean indicating if the line is orthogonal (ie the perimeter point should be an orthogonal projection on the perimeter). See the implementation of the other perimeters for details.

**Pull request closed without merging**
