### PR TITLE
Fix for bad CRC in PNG exports (issue jgraph#97)

### PR DESCRIPTION
**Pull request by simonedlund**

### CODE REVIEW

**Comment by alderg** [comment]
This does not fix the problem for me. Tested with "identify" (ImageMagick), I still get "zTXt: incorrect header check" error message.

**Comment by simonedlund** [comment]
Yes, you will get the "zTXt: incorrect header check", but without my fix you will get: "zTXt: CRC error".
There is some other issue with how the zTXt chunk is stored, and fixing that problem will most likely cause incompatibility problems. My fix fixes the CRC error.

Importing with python (PIL) works fine, using the commands in the issue report.

Also, if you review the code, you'll see that I replaced `data[n]` with `data.charCodeAt(n)`, which is the correct way to get the char codes from a string in js:
```
> data = 'zTXt'
'zTXt'
> data[0] ^ 0
0
> data.charCodeAt(0) ^ 0
122
```
Have for instance a look at this:
https://stackoverflow.com/questions/18638900/javascript-crc32

**Comment by alderg** [comment]
Got it, thanks for the clarification! Will merge into the next release.

**Comment by simonedlund** [comment]
@alderg, if you want to fix the incorrect headercheck issue with png images you would need to replace deflateRaw/inflateRaw with deflate/inflate, but as I said, this will cause incompatibilities.

One possible solution would be to fix the export and rename the chunk to e.g. "mxGraphModel2", and keep both versions of the import.

**Pull request closed without merging**
