### PR TITLE
Fix GitLabClient.js get wrong draw.io host path when window.location href contains "/"

### PR DESCRIPTION
**Pull request by ProNic-QY**
relate to https://github.com/jgraph/drawio/issues/493#issuecomment-550272829. For example, use 
`https://MyDraw.io/?gitlab=https://MyGitLab.com&gitlab-id=AppId` to access my self host draw.io server, GitlabClient.js generate `rediretUrl` query parameter will be `https://MyDraw.io/?gitlab=https://gitlab.html`, correct should be `https://MyDraw.io/gitlab.html`.

### CODE REVIEW

**Comment by davidjgraph** [comment]
We can't merge this now since you've written your custom values to the diff.

If you want to set variable, use preConfig.js to write them without having to rebuild.

**Comment by ProNic-QY** [comment]
> We can't merge this now since you've written your custom values to the diff.
> 
> If you want to set variable, use preConfig.js to write them without having to rebuild.

Sorry, the custom values setting was caused by my temporary test, I forgot it will be updated to this PR.
You can reconsider whether shoude accept the first commit for gitlab redirect url fix, if necessary I can reopen a new PR.

**Comment by davidjgraph** [comment]
What's an example URL where your first change fixes it?

**Comment by davidjgraph** [comment]
Ah sorry, you posted in top post, a lot of issues, reading too fast :).

**Comment by davidjgraph** [comment]
OK, the URL parameters must be URI encoded. If we're not decoded them, that's actually a different bug. Try again with properly encoded URL parameters

**Comment by ProNic-QY** [comment]
> Ah sorry, you posted in top post, a lot of issues, reading too fast :).

You are right, without URLencoding, `href.lastIndexOf ('/'))` may not find the correct route for current Draw.io.

**Comment by ProNic-QY** [comment]
You are right, without URLencoding, href.lastIndexOf ('/')) may not find the correct route for current Draw.io.

**Pull request closed without merging**
