### PR TITLE
Add support for GitLab as storage

### PR DESCRIPTION
**Pull request by duydao**
clientId for GitLab are missing. If you want to use this pull request, please create an app on gitlab and set the client ids in GitLabClient.js analog to the GitHub Apps.

### CODE REVIEW

**Comment by alderg** [comment]
Thanks! This will go into the next release. BTW: Did you work on the Bitbucket integration?

**Comment by duydao** [comment]
@alderg Great news, thanks!

Indeed, I'll do some additional testing before sending the pull request. I'm also working on a small feature to create subfolders when choosing to save to a gitlab repo. If there is any interest, I will add it to github and BB as well.

**Comment by alderg** [comment]
It's deployed. Sure, adding subfolders in GitHub and BB would be useful! Thanks again! Do you want public credit on social media?

**Comment by alderg** [comment]
GitLab seems to have problems with UTF characters (try "äöü" as the page name, save and refresh), if you have an idea on how to fix that please let me know!

**Comment by duydao** [comment]
@alderg not necessary, thanks!

**Comment by alderg** [comment]
Why is the "master" branch hardcoded when parsing the path? See https://github.com/jgraph/drawio/blob/master/src/main/webapp/js/diagramly/GitLabClient.js#L237

**Comment by duydao** [comment]
This is for supporting groups and subgroups on gitlab.

For example:

mygroup/mysubgroup/myrepo/master/path/to/my/drawio/file

Everything before master belongs to the _repository_ path, and has to be [urlencoded](https://github.com/jgraph/drawio/blob/master/src/main/webapp/js/diagramly/GitLabClient.js#L253).

The repo ref could contain slashes as well, e.g. feature/XYZ-123. The easiest way was to support the master branch.

I agree that there should be a better way, I just didn't see a clean way to add a parameter to GitLabClient.prototype.getFile method without breaking compatibility for other things.

Do you have a suggestion?

**Comment by alderg** [comment]
Thanks for the clarification. We'll have to backtrack on the tokens and use the first index that works. Haven't looked at slashed in branches yet...

**Comment by alderg** [comment]
I'll fix.

**Comment by StripedBanana** [comment]
Hi, does this PR include support for self-hosted GitLab instances ?

**Comment by davidjgraph** [comment]
Self-hosted should work. We haven't tested ourselves. If any problems create a new issue.

**Pull request closed without merging**
