### PR TITLE
Adds basic command line support and fixes a small bug saving documents.

### PR DESCRIPTION
**Pull request by AleixDev**
The proposed arguments are:
```
draw.io
draw.io test1.xml

draw.io -c
draw.io -c test1.xml
draw.io -h
draw.io -V

# (Extended version)
draw.io --create-if-not-exists
draw.io --create-if-not-exists test1.xml
draw.io --help
draw.io --version
```

This should resolve jgraph/drawio-desktop#4

### CODE REVIEW

**Comment by alderg** [comment]
Shouldn't -c be implicit if a path is used that does not exist?

**Comment by AleixDev** [comment]
Well probably yes, depends on what you prefer.. I just made this an option because there are some programs like Gimp that shows a popup error when trying to open an inexistent file, and others like Atom that creates a blank document without actually saving it to disk. 

For me it's okay to drop the flag and just create the document, but then I would remove the line that saves it to disk until you manually click the save button, so it doesn't create unwanted files by default.

In the other hand, I used this flag (when a path is not passed) to allow opening directly a new blank document or showing startup menu. I think that this is useful because sometimes you don't want that the menu appears at the startup, but this probably should be a different flag name.

**Comment by AleixDev** [comment]
(I hope you get the point, as you might notice I'm not a native english speaker)

**Comment by alderg** [comment]
OK, got it. However, I tried to merge this PR and getting "Cannot find module 'commander'" on npm install.

**Comment by AleixDev** [comment]
Mmm.. It's strange, I've just tested on a new Ubuntu machine and it just works without problems:
```
git clone https://github.com/AleixDev/drawio.git /tmp/drawio/

cd /tmp/drawio/war

npm install
```

What operating system are you using? What happens if you try to install the package directly with `npm install commander`?

**Comment by alderg** [comment]
Works now. We'll add this to the next release. Thanks for the contribution!

**Pull request closed without merging**
