### PR TITLE
Fix gitlab auth fail,which always get a "Access denied" error dialog.

### PR DESCRIPTION
**Pull request by GCChen**
Change gitlab auth request param from 'code' to 'token'. Change gitlab remembered data from boolean value to real access token.

### CODE REVIEW

**Comment by davidjgraph** [comment]
Thanks for this. Exactly what issue does this solve? Have you fully tested all Gitlab login cases against the new code?

**Comment by GCChen** [comment]
Hi. I wanted to save drawio file to the local gitlab instance I made before. But when I verified gitlab application through drawio gitlab web page, I always got a "Access denied" error dialog. So I used dev mode to see what happend. I found that request to "/oauth/authorize" with param "response_type=code", will get a response with "code=xxx", not with "access_token=xxx", which is required by "gitlab.html". Then I searched some issues about that request. At last I found that when changed the request param from "response_type=code" to "response_type=token", you wound get a response with "access_token".

**Comment by GCChen** [comment]
Btw, the code of "gitlab.html", which is the callback url for the gitlab application, only return the "access_token". It's a token number, not a json object. So I changed the code which to save token in "GitLabClient.js".

**Comment by GCChen** [comment]
I have tested the new code with open, add draw.io file to my local gitlab instance and to gitlab.com successfully.

**Comment by davidjgraph** [comment]
OK thanks for the clarification. I don't have time to look into this currently, hopefully another member of the team will get time to look.

**Comment by davidjgraph** [comment]
How are you running the server part of this project, do you have the gitlab servlet running and responding correctly?

**Comment by ashrafteleb** [comment]
Sorry, we cannot accept this PR. We've moved to code response based on GitLab recommendation and it is indeed much more secure. Token is deprecated and will soon get removed by GitLab.

**Pull request closed without merging**
