### PR TITLE
Fixed an issue where images with file sizes between 77KB and 100KB would be resized.

### PR DESCRIPTION
**Pull request by daisuke-yoshimoto**
### Overview

* This PR fixes an issue where images with file sizes ranging from 77KB to 100KB were being resized

### Prerequisite specifications

1. If the file size is larger than 100 KB, a confirmation message appears asking if you want to resize the image.
2. If the file size is less than 100KB, the confirmation dialog is not displayed and the image is imported as is. The image is imported without resizing.

### Detail

* There is a difference in the method of obtaining the file size between the decision to display the confirmation dialog for resizing at the time of image upload and the decision to actually resize the image.
* As a result, when an image is uploaded, it may be resized even though the confirmation dialog for resizing is not displayed when the image is uploaded.

* In order to display the resize confirmation dialog, the actual binary file size of the image is checked.
    * https://github.com/jgraph/drawio/blob/916290d3e8c9650f040ef76fb9da66fc9899ce16/src/main/webapp/js/diagramly/EditorUi.js#L8010
* On the other hand, in the process of determining whether or not to actually resize the image, the file size of the image after it has been base64 encoded is checked.
    * https://github.com/jgraph/drawio/blob/916290d3e8c9650f040ef76fb9da66fc9899ce16/src/main/webapp/js/diagramly/EditorUi.js#L8307

### Steps to reproduce

1. Drag and drop the following image onto the drawio canvas.
test
2. The image is resized without showing the resize confirmation dialog.

### Before fix & After fix

* Before fix

before_fix

* After fix

after_fix

## Solution

* I've also modified it to check the size of the original image data instead of the base64-encoded data when checking whether to actually resize it.

### CODE REVIEW

**Comment by daisuke-yoshimoto** [comment]
@davidjgraph

Can you please review this pull request?

**Comment by alderg** [comment]
Thanks for the PR. This will be merged via the main repo.

**Comment by daisuke-yoshimoto** [comment]
@alderg 
Thank you for this PR merge and release.
https://github.com/jgraph/drawio/releases/tag/v13.7.8
https://github.com/jgraph/drawio/compare/v13.7.7...v13.7.8#diff-84c7eaa80e7554c058de9ed854661d93

By the way, when will the drawio-desktop incorporating this fix be released?

**Comment by davidjgraph** [comment]
The desktop build is in the release process for 13.7.8

**Comment by daisuke-yoshimoto** [comment]
@alderg @davidjgraph 
Thank you for the release 13.7.8 👍 
https://github.com/jgraph/drawio-desktop/releases/tag/v13.7.8

**Pull request closed without merging**
