### PR TITLE
Add generic isometric shape to be used as container

### PR DESCRIPTION
**Pull request by eduardomourar**
This is related to #339 and aims to solve the issue by adding a new isometric library so that it can be used as container for both other sub-shapes or images. It requires the change in mxGraph [here](https://github.com/jgraph/mxgraph2/pull/1).

isometric

### CODE REVIEW

**Comment by eduardomourar** [comment]
I have created a [PR](https://bitbucket.org/jgraph/mxgraph2/pull-requests/1) for mxGraph in Bitbucket, but it doesn't seem to be visible to anyone. @davidjgraph and @alderg , could you guys take a look into it, please? This is a very small change that could benefit others.

**Comment by eduardomourar** [comment]
I have rewritten the previous code by implementing the proper isometric projection of any given shape/image and created a [PR](https://github.com/jgraph/mxgraph2/pull/1) for mxGraph. @davidjgraph and @alderg , could you guys take a look into it, please?

**Comment by alderg** [comment]
Nice! We'll have to think about this to make it work with the Java and .Net APIs.

**Comment by JosselinBeaumont** [comment]
Hi, I don't see changes on draw.io. How Can I look at this ?

**Comment by davidjgraph** [comment]
The PR isn't merged...

**Comment by JosselinBeaumont** [comment]
Ok...
And when will it be ?

Le mer. 17 juil. 2019 à 11:20, David Benson <notifications@github.com> a
écrit :

**Comment by davidjgraph** [comment]
Sooner, if you review and merge it.

**Comment by JosselinBeaumont** [comment]
I'll wait for you to do it

Le mer. 17 juil. 2019 à 11:24, David Benson <notifications@github.com> a
écrit :

**Comment by davidjgraph** [comment]
To accept a large piece of functionality we need either the original author to commit to maintaining it forever (not realistic) or one of the project team to agree to become responsible for it. This is commercial grade software, we cannot add parts in that are not complete and maintained.

The maintenance effort of software is invariably somewhat more than the effort of producing the initial version, and knowing this, nobody on the team wants to take it over.

For this particular functionality, there is a mass of side-effects and additional work required, handles, boundaries, text rendering, server-side image export, edge routing, the back-end APIs in Java and .NET, etc. My personal view is it's outside of the intended scope of the project and it's a massive task.

I'm sorry you've gone to this effort, but at this time we can't accept it. Your best option is either extend the mxShape class and keep the changes local, or fork the project and maintain it there.

**Comment by duraki** [comment]
@eduardomourar this is awesome PR! I'll fork your PR and promote it whenever it needs a promotion. Crazy that drawio team don't want to support this. Shame!

**Comment by eduardomourar** [comment]
@duraki , I think this other PR is also important to you then: https://github.com/jgraph/mxgraph2/pull/1. We should ask that to be merged so that you don't have to keep both forks up-to-date.

**Comment by woyczek** [comment]
It is a pity this MR hasn’t been accepted. We really miss this feature in draw.io.

**Pull request closed without merging**
