### PR TITLE
For jgraph/drawio#159

### PR DESCRIPTION
**Pull request by kannangce**
Committing back the docker file that was accidentally deleted by @alderg . Reference(https://github.com/jgraph/drawio/commit/9c86bba29e9ad61a6faa373776360acf86b5872c)

### CODE REVIEW

**Comment by kannangce** [comment]
@davidjgraph PR for the same issue #159

**Comment by alderg** [comment]
We will put this into etc/docker in the next release. Thanks for the PR!

**Comment by kannangce** [comment]
@alderg  how can we track this? Can I create an issue for this?

**Comment by davidjgraph** [comment]
https://github.com/jgraph/drawio/tree/master/etc/docker

**Pull request closed without merging**
