### PR TITLE
single file change for to sql and from sql plugin

### PR DESCRIPTION
**Pull request by lastlink**
## Updates
* please use the 3rd party up to date project [sqltooling-drawio](https://github.com/funktechno/sqltooling-drawio/tree/main) with the latest [sql](https://raw.githubusercontent.com/funktechno/sqltooling-drawio/main/dist/sql.js) plugin (and [nosql](https://raw.githubusercontent.com/funktechno/sqltooling-drawio/main/dist/nosql.js) for openapi spec)

## Notes:
* I know this will be rejected since this is close contribution
* I've updated this from the prs so all you have to do is update the plugin `src/main/webapp/plugins/sql.js` file to install it locally.
* I'm aware that using a native tool for your db may be better for uml diagrams.
* There are many workflows that this works, you can do [code share](https://marketplace.visualstudio.com/items?itemName=hediet.vscode-drawio) from vscode for collaboration after importing your drawio file from a sql table schema export
* setup see wiki from branch https://github.com/lastlink/drawio/wiki/Getting-Started
* It's easiest to setup in the drawio desktop, to use the plugin https://github.com/jgraph/drawio-desktop
  * `git clone --recursive https://github.com/jgraph/drawio-desktop.git` 1 gb clone btw
  * `npm install`
  * update `drawio/src/main/webapp/plugins/sql.js` with changes from [branch](https://github.com/lastlink/drawio/blob/patch-2/src/main/webapp/plugins/sql.js)
  * `npm start` run application 
  * add plugin in `Extras > Plugins > Add` select sql
  * close application and reopen. Plugin is installed
* you can find the menu buttons in `File > Export As > To SQL` or `Arrange > Insert > From SQL`
## References
* #3083, #3092, #3091

### CODE REVIEW

**Comment by davidjgraph** [comment]
We'll look into whether an exception can be made here as it's a significant amount of work to be rejected.

**Comment by steel198513** [comment]
I ran through this process but the To SQL option was not showing up on the menu

**Comment by lastlink** [comment]
@steel198513 try looking in File > Export As

**Comment by lastlink** [comment]
@karthiart did you pull/copy the updates for the file from this pr? Otherwise you won't have my changes.

**Comment by karthiart** [comment]
@lastlink Thanks for your response. If you don't mind, can you let me know how to implement it from this pr? Because i dont know how to do these below steps.

It's easiest to setup in the drawio desktop, to use the plugin https://github.com/jgraph/drawio-desktop

- git clone --recursive https://github.com/jgraph/drawio-desktop.git 1 gb clone btw

- npm install

- update drawio/src/main/webapp/plugins/sql.js with changes from [branch](https://github.com/lastlink/drawio/blob/patch-2/src/main/webapp/plugins/sql.js)

- npm start run application

**Comment by karthiart** [comment]
When i did npm start. I am getting this attached error message. Any help?
error

**Comment by ChrisNolan** [comment]
Thanks for making this available.  I was just coming to post some changes that allowed [Spaces in Column Names] to get parsed correctly but yours is so much more robust.  

I wanted to share for others coming to this that want just the functionality, but aren't too comfortable with code.  You can get a local copy of the plugin if you modify your draw.io desktop shortcut to include a ``--enable-plugins``, e.g. edit your start menu shortcut to be ``"C:\Program Files\draw.io\draw.io.exe" --enable-plugins``.  Then when you do the 'add' under the "Extras -> Plugins" menu there will be an option to add a file from disk instead, and you just need to save a 'raw' copy of the 'sql.js' file included here and restart your program to get access to all this functionality.

**Comment by andrewchch** [comment]
> We'll look into whether an exception can be made here as it's a significant amount of work to be rejected.

That would be awesome! Importing schema with FK relationship connectors is a really useful feature in Lucid and I'd love to see it here. Great work, @lastlink !

**Comment by andrewchch** [comment]
> Thanks for making this available. I was just coming to post some changes that allowed [Spaces in Column Names] to get parsed correctly but yours is so much more robust.
> 
> I wanted to share for others coming to this that want just the functionality, but aren't too comfortable with code. You can get a local copy of the plugin if you modify your draw.io desktop shortcut to include a `--enable-plugins`, e.g. edit your start menu shortcut to be `"C:\Program Files\draw.io\draw.io.exe" --enable-plugins`. Then when you do the 'add' under the "Extras -> Plugins" menu there will be an option to add a file from disk instead, and you just need to save a 'raw' copy of the 'sql.js' file included here and restart your program to get access to all this functionality.

This worked great, thanks @ChrisNolan

**Comment by lastlink** [comment]
Steps for running external plugin on mac https://github.com/ariel-bentu/tam-drawio/blob/main/mac-pass-arg.md

**Comment by lastlink** [comment]
You can run in vscode drawio extension as well.

settings.json
```json
  "hediet.vscode-drawio.plugins": [
    {
      "file": "<path>\\plugins\\sql.js"
    }
  ],
```

**Comment by lastlink** [comment]
I'm no longer maintaining this pr, but I've made a separate repo for the plugin. I've added support for vscode drawio plugin compatibility.

See:
 * https://github.com/funktechno/sqltooling-drawio/tree/main and
 * [sql.js](https://raw.githubusercontent.com/funktechno/sqltooling-drawio/main/dist/sql.js)

**Pull request closed without merging**
