### PR TITLE
Animations plugin : new features and bug fixes

### PR DESCRIPTION
**Pull request by smazuir**
New features
  - Multiple animations
  - Set scale in animation
  - Center on cell
  - Highlight cells
  - Control bar in lightbox mode, with play/pause, prev step, next step, restart anim, animation selector
  - Support for comments in scripts (// comment)
  - Support for layers

Bug fixes
  - Stencil shapes with alpha still showed up on init
  - fading not applied correctly on foreign objects (text boxes...) because foreignObject element not correctly positionned => added a temporary overlay for animation

### CODE REVIEW

**Comment by davidjgraph** [comment]
Thanks for the submission. When someone is free we'll take a look through to review the functionality and security of the changes.

**Comment by smazuir** [comment]
Hi @davidjgraph, some news about this code review? :)

**Comment by davidjgraph** [comment]
Hi,

Thanks for your submission. Unfortunately, we're going to have to change our policy on PRs. We just can't accept copyrightable contributions to the codebase and so will have to reject all non trivial PRs.

Apologies for this, we will make that clear on the README.

**Comment by smazuir** [comment]
Hi,

It's sad that users can't contribute improving an enhancing this app anymore, especially concerning plugins...
At least, will there be a way to use external pluggins ? It's currently blocked by CSP policy... leaving us with no way to devellop and / or use custom pluggins. I was using draw.io and then diagrams.net to draw software architecture diagrams professionaly, and used my own custom pluggins to add interractivity to my diagrams, and to prepare presentations for developpers focusing on features with anotations (using animations with pan & zoom).
I'm probably going to need some other tools to do what I used to do with draw.io... :(

**Comment by smazuir** [comment]
Hi @davidjgraph,

Having a closer look, I didn't see what "copyrightable material" you talked about in this PR ? It's only based on native framework, adding some features, but not including any new external library or other material that may be "copyrightable material"...

Could you enlighten me about what is wrong with this PR? Maybe I could rework it to be compliant ?

Thanks by advance.

**Comment by davidjgraph** [comment]
There's nothing with it. When you write code it's implicitly copyrighted to you. The problem is that it's copyright to you, not to someone else. The entire codebase is copyrighted to JGraph, changing that isn't simple.

**Comment by smazuir** [comment]
Isn't there a way to indicate, maybe with a comment in code header, that I give rights to JGraph for this contribution ?

**Comment by davidjgraph** [comment]
Assigning copyright could be done, yes. But, next the issue is that we are legally responsible for the security of your code when it's deployed app.diagrams.net. If it has a hole and data gets stolen, we gets sued. Have you completely analysed the code for security issues? Are you willing to take liablity for the code.

I know the answer is no, but you see the problem. In an open source desktop app, there aren't these problems. On a codebase that we deploy to millions of users every day, we take significant risk.

I, personally, don't want to take reponsibility for your code. If another member of the team is willing to be personally liable then they can merge it.

**Comment by gitown** [comment]
@davidjgraph it's really unfortunate to see such great feature not accpeted to be reviewed/merged into diagrams.net!
@smazuir If you could create a feauture request for those functionnalities and a link to your PR that will be really nice.

I'm crossing my fingers to see such great features implemented into diagrams.net

**Comment by davidjgraph** [comment]
@gitown are you willing to fund all bounties for all security vulnerabilities in this code?

**Comment by gitown** [comment]
@davidjgraph I didn't read the code to know if it contains vulnerabilities!
I'm just kindly asking to consider adding these features as they're very useful features and I'm pretty sure that many users will be happy to see them in diagrams.net!

**Comment by davidjgraph** [comment]
So, I pay for any vulnerability bounties on someone else's code? I don't understand, why would I do this?

**Comment by gitown** [comment]
@davidjgraph I don't understand your point of talking about vulnerability bounty and paying for that! If that code contains vulnerabilities don't accept that PR. Full Stop.
Beside that code that contains the vulnerabilities, the community aren't allowed to ask for new features and improvements for your product? I understand that the community aren't allowed to do a PR, but also features request are not allowed?

**Comment by gitown** [comment]
@davidjgraph I don't understand your point of talking about vulnerability bounty and paying for that! If that code contains vulnerabilities don't accept that PR. Simple.
Beside that code that contains the vulnerabilities, the community aren't allowed to ask for new features and improvements for your product? I understand that the community aren't allowed to do a PR, but also features request are not allowed?

**Comment by davidjgraph** [comment]
```
@davidjgraph I don't understand your point of talking about vulnerability bounty and paying for that! If that code contains vulnerabilities don't accept that PR. Simple.
Beside that code that contains the vulnerabilities, the community aren't allowed to ask for new features and improvements for your product? I understand that the community aren't allowed to do a PR, but also features request are not allowed?
```

Seeing security issues in non-trivial PRs isn't simple. I can see a console.log left in, so this code hasn't been reviewed properly.

You are welcome to ask for new features, but this is a PR, not a new feature issue, that would be posted at https://github.com/jgraph/drawio/issues.

**Pull request closed without merging**
